build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage -c phpunit.xml'
                coverage:
                    file: 'coverage'
                    format: 'clover'
